# Builds plugins\index.json - the catalogue the in-app plugin browser reads.
#
# Two data sources, neither of which we have to mirror:
#   * the upstream wiki lists which plugins exist (name, repo, description);
#   * the GitHub API says which .qlplugin each repo ships, and hands us the
#     sha256 of that asset in its `digest` field, so the catalogue can pin the
#     exact bytes without downloading a single one of them.
#
# Usage:  pwsh -NoProfile -File .\Scripts\build-plugin-index.ps1
# Needs:  gh (authenticated) - the API calls are unauthenticated-rate-limit bound otherwise.
#
# Entries whose repo ships no .qlplugin asset are reported and skipped, so the
# app never offers an install it cannot finish.

param(
    [string]$OutFile = (Join-Path (Split-Path -Parent $PSScriptRoot) 'plugins\index.json'),
    [string]$WikiUrl = 'https://raw.githubusercontent.com/wiki/QL-Win/QuickLook/Available-Plugins.md',
    # Assets uploaded before GitHub started reporting a digest have none, so the
    # only way to pin them is to fetch the file once and hash it ourselves.
    # ~15 of the ~45 plugins need this; the total is well under 100 MB.
    [switch]$SkipHashing
)

$ErrorActionPreference = 'Stop'

Write-Host "Reading $WikiUrl" -ForegroundColor Cyan
$wiki = (Invoke-WebRequest -Uri $WikiUrl -UseBasicParsing -TimeoutSec 30).Content -replace '\r', ''

# Only the first table ("## List of plugins"); the legacy table below it is
# struck through and marked as unmaintained, so it is deliberately skipped.
$rows = ($wiki -split "`n") | Where-Object { $_ -match '^\[' }

$plugins = New-Object System.Collections.Generic.List[object]
$skipped = New-Object System.Collections.Generic.List[string]

foreach ($row in $rows) {
    if ($row -notmatch '^\[(?<name>[^\]]+)\]\((?<url>https://github\.com/[^\)]+)\)') {
        continue
    }

    $name = $Matches['name'].Trim()

    # "owner/repo" out of the link, ignoring any trailing /releases path.
    $parts = ($Matches['url'] -replace '^https://github\.com/', '') -split '/'
    if ($parts.Count -lt 2) { continue }
    $slug = "$($parts[0])/$($parts[1])"

    # The description is whatever follows the download cell; keeping it as the
    # last column survives descriptions that contain a pipe of their own.
    $cells = $row -split '\|'
    $description = ($cells[-1] -replace '\s+', ' ').Trim()

    try {
        $release = gh api "repos/$slug/releases/latest" 2>$null | ConvertFrom-Json
    }
    catch {
        $release = $null
    }

    if (-not $release) {
        $skipped.Add("$name ($slug): no published release")
        continue
    }

    $asset = $release.assets | Where-Object { $_.name -like '*.qlplugin' } |
        Sort-Object -Property @{ Expression = { $_.name -eq "$($parts[1]).qlplugin" } } -Descending |
        Select-Object -First 1

    if (-not $asset) {
        $skipped.Add("$name ($slug): release $($release.tag_name) ships no .qlplugin")
        continue
    }

    # "sha256:abc..." -> "abc..."
    $sha = ($asset.digest -replace '^sha256:', '')

    if ($sha -notmatch '^[0-9a-fA-F]{64}$') {
        if ($SkipHashing) {
            $skipped.Add("$name ($slug): asset has no sha256 digest")
            continue
        }

        # Older asset: download it once and hash it, so every catalogue entry is
        # still pinned to exact bytes.
        $temp = Join-Path ([System.IO.Path]::GetTempPath()) $asset.name
        Write-Host ("  hashing {0} ..." -f $asset.name) -ForegroundColor DarkGray
        Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $temp -UseBasicParsing
        $sha = (Get-FileHash -LiteralPath $temp -Algorithm SHA256).Hash
        Remove-Item -LiteralPath $temp -Force
    }

    $plugins.Add([pscustomobject]@{
            id          = $parts[1]
            name        = $name
            publisher   = $parts[0]
            description = $description
            repoUrl     = "https://github.com/$slug"
            version     = $release.tag_name
            published   = $release.published_at
            asset       = $asset.name
            size        = [int64]$asset.size
            sha256      = $sha.ToLowerInvariant()
            url         = $asset.browser_download_url
        })

    Write-Host ("  {0,-34} {1,-10} {2,8:N0} KB" -f $name, $release.tag_name, ($asset.size / 1KB))
}

$index = [pscustomobject]@{
    schema    = 1
    generated = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
    source    = 'https://github.com/QL-Win/QuickLook/wiki/Available-Plugins'
    note      = 'Generated by Scripts/build-plugin-index.ps1. Each entry ships a .qlplugin from its own repository; nothing is mirrored here.'
    plugins   = @($plugins | Sort-Object name)
}

$dir = Split-Path -Parent $OutFile
if (-not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Path $dir | Out-Null
}

$index | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $OutFile -Encoding UTF8

Write-Host ''
Write-Host ("Wrote {0} plugins to {1}" -f $plugins.Count, $OutFile) -ForegroundColor Green
if ($skipped.Count -gt 0) {
    Write-Host ("Skipped {0}:" -f $skipped.Count) -ForegroundColor Yellow
    $skipped | ForEach-Object { Write-Host "  $_" -ForegroundColor DarkYellow }
}
