$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$tag = & git -C $repoRoot describe --always --tags "--abbrev=0" --exclude latest 2>$null
$revision = & git -C $repoRoot describe --always --tags --exclude latest 2>$null

# When the tree is not inside a git repository (for example a source snapshot
# exported from an archive), fall back to a valid numeric version so the build
# still succeeds instead of leaving a missing GitVersion.cs.
if ([string]::IsNullOrWhiteSpace($tag) -or $tag -notmatch '^\d+\.\d+\.\d+') {
    $existing = Join-Path $PSScriptRoot '..\GitVersion.cs'
    if (Test-Path $existing) {
        $content = Get-Content $existing -Raw
        if ($content -match 'AssemblyVersion\("(\d+\.\d+\.\d+)"\)') {
            # Keep an existing valid version (e.g. a source snapshot built
            # outside a git repository) instead of overwriting it.
            Write-Warning "update-version: git describe failed; keeping existing GitVersion.cs"
            exit 0
        }
    }

    $tag = '0.0.0'
    $revision = '0.0.0'
    Write-Warning "update-version: git describe failed; using fallback version $tag"
}

$text = @"
// This file is generated by update-version.ps1

using System.Reflection;

[assembly: AssemblyVersion("$tag")]
[assembly: AssemblyInformationalVersion("$revision")]
"@

$text | Out-File $PSScriptRoot\..\GitVersion.cs -Encoding utf8
