$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$tag = & git -C $repoRoot describe --always --tags "--abbrev=0" --exclude latest 2>$null
$revision = & git -C $repoRoot describe --always --tags --exclude latest 2>$null

if ([string]::IsNullOrWhiteSpace($tag) -or $tag -notmatch '^\d+\.\d+\.\d+') {
    Write-Warning "update-version: git describe failed; keeping existing GitVersion.cs"
    exit 0
}

$text = @"
// This file is generated by update-version.ps1 
 
using System.Reflection;
 
[assembly: AssemblyVersion("$tag")]
[assembly: AssemblyInformationalVersion("$revision")]
"@

$text | Out-File $PSScriptRoot\..\GitVersion.cs -Encoding utf8
